[[constraint]]
  name = "github.com/botopolis/bot"
  version = "0.3.0"

[[constraint]]
  name = "github.com/go-redis/cache"
  version = "6.3.2"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.8.3"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "3.2.5"
